ARG SQY_VERSION=latest

FROM sqy/trusty/base:${SQY_VERSION} as base
FROM sqy/trusty/encoders-static:${SQY_VERSION} as encoders
FROM sqy/trusty/utils-static:${SQY_VERSION} as utils

COPY --from=base /usr/ /usr/
COPY --from=encoders /usr/ /usr/
COPY --from=utils /usr/ /usr/

WORKDIR /build

# build sqeazy
RUN git clone https://github.com/sqeazy/sqeazy.git\
    cd sqeazy
    git remote add psteinb https://github.com/psteinb/sqeazy.git

# Run app.py when the container launches
CMD ["bash"]
